module.exports = {
  windowsSizeX: 1600,
  windowsSizeY: 1200,
  oneSecondWaitTime: 1,
  twoSecondWaitTime: 2,
  fiveSecondWaitTime: 5,
  sevenSecondWaitTime: 7,
  nineSecondWaitTime: 9,
  tenSecondWaitTime: 10,
  fifteenSecondWaitTime: 10,
  twentySecondWaitTime: 10,
  thirtySecondWaitTime: 10,
  fortySecondWaitTime: 10,
  retryCountForStep: 4,
  CCDCaseNumber: 16,
  minTimeout: 1000,
  maxTimeout: 3000,
  defaultNumberOfRetries: 2,
  oneMinute: 60
};
