payment-api:
  releaseNameOverride: ${SERVICE_NAME}-payment-api
  java:
    releaseNameOverride: ${SERVICE_NAME}-payment-api
    image: hmcts.azurecr.io/hmcts/payment-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://${SERVICE_NAME}-payment-db:5432/payment
      AUTH_PROVIDER_SERVICE_CLIENT_BASEURL: http://rpe-service-auth-provider-aat.service.core-compute-aat.internal
      AUTH_IDAM_CLIENT_BASEURL: https://idam-api.aat.platform.hmcts.net
  postgresql:

nodejs:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  applicationPort: 3000
  environment:
    REFORM_TEAM: ccpay
    REFORM_SERVICE_NAME: ccpay-bubble-frontend
    REFORM_ENVIRONMENT: preview
    NODE_ENV: production

    CCPAY_BUBBLE_MICROSERVICE: ccpay_bubble
    CCPAY_BUBBLE_URL: https://${SERVICE_FQDN}
    PAYHUB_API_URL: http://${SERVICE_NAME}-payment-api

    S2S_KEY: ${PAYBUBBLE_S2S_TOTP_SECRET}
    IDAM_CLIENT_SECRET: ${IDAM_CLIENT_SECRET}

    S2S_URL: http://rpe-service-auth-provider-aat.service.core-compute-aat.internal
    IDAM_API_URL: https://idam-api.aat.platform.hmcts.net
    IDAM_AUTHENTICATION_WEB_URL: https://idam-web-public.aat.platform.hmcts.net/login
    
    APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY}
tags:
  - idam-pr
idam-pr:
  service:
    name: pay-bubble # this is the label (name) of the service as configured in IDAM.
    redirect_uri: https://${SERVICE_FQDN}/oauth2/callback # this is the application callback URL where IDAM will send back the authentication code. SERVICE_FQDN is injected by Jenkins.
