nodejs:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  applicationPort: 3000
  memoryRequests: 64Mi
  cpuRequests: 0.2
  memoryLimits: 256Mi
  cpuLimits: 1
  environment:
    REFORM_TEAM: ccpay
    REFORM_SERVICE_NAME: ccpay-bubble-frontend
    REFORM_ENVIRONMENT: preview
    NODE_ENV: production
    CCPAY_BUBBLE_MICROSERVICE: ccpay_bubble
