protocol: http
security:
  referrerPolicy: origin
idam:
  client_id: paybubble
  login_url: https://idam-web-public.demo.platform.hmcts.net/login
  api_url: https://idam-api.demo.platform.hmcts.net
session:
  cookieName: SESSION_ID
environment:
  ldPrefix: FEdemo
  currentEnv: https://paymentoutcome-web.demo.platform.hmcts.net
ccpaybubble:
  url: https://localhost
  defaultPort: 3000
  microservice: ccpay_bubble
pcipalantenna:
  url: https://localhost:3000/ccd-search
  microservice: ccpay_bubble
s2s:
  url: http://rpe-service-auth-provider-demo.service.core-compute-demo.internal
payhub:
  url: http://payment-api-demo.service.core-compute-demo.internal
bulkscan:
  url: http://localhost
  defaultPort: 8080
refunds:
  url: http://ccpay-refunds-api-demo.service.core-compute-demo.internal
notification:
  url: http://ccpay-notifications-service-demo.service.core-compute-demo.internal
waystopay:
  url: https://paymentoutcome-web.demo.platform.hmcts.net/payment
postcodelookup:
  url: https://api.os.uk/search/places/v1
appInsights:
  roleName: paybubble
e2e:
  frontendUrl: http://localhost:4200/
  waitForTimeoutValue: 2600
  waitForActionValue: 2000
certs:
  key: ./localhost-ssl/localhost.key
  crt: ./localhost-ssl/localhost.crt
fee:
  feeRegistrationUrl: http://fees-register-api-demo.service.core-compute-demo.internal/fees-register/fees
  feeJurisdictionUrl: http://fees-register-api-demo.service.core-compute-demo.internal/jurisdictions
ccd:
  url: http://ccd-data-store-api-demo.service.core-compute-demo.internal
secrets:
  ccpay:
    paybubble-s2s-secret: G5XTFNBUW4P6ZP4F
    paybubble-idam-client-secret: NVYEC2X7XFSRENTU
    launch-darkly-client-id: 5f227f4df775300ba82996dc
    postcode-address-lookup-id: PKQqwTTaCzBYQRJMD1pAQUEaGYGcIEdT
    AppInsightsInstrumentationKey: AppInsightsInstrumentationKey
