#external_host_name ="paybubble.aat.platform.hmcts.net"
capacity = "2"
idam_api_url = "https://preprod-idamapi.reform.hmcts.net:3511"
authentication_web_url = "https://idam.preprod.ccidam.reform.hmcts.net/login"
vault_section = "preprod"
