#external_host_name ="paybubble.aat.platform.hmcts.net"
capacity = "2"
idam_api_url = "https://idam-api.aat.platform.hmcts.net"
authentication_web_url = "https://idam-web-public.aat.platform.hmcts.net"
vault_section = "preprod"
