#external_host_name ="paybubble.demo.platform.hmcts.net"
idam_api_url = "https://idam-api.aat.platform.hmcts.net"
authentication_web_url = "https://idam-web-public.demo.platform.hmcts.net"
capacity = "1"
vault_section = "preprod"
