nodejs:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  applicationPort: 3000
  memoryRequests: 64Mi
  cpuRequests: 0.2
  memoryLimits: 256Mi
  cpuLimits: 1
  environment:
    REFORM_TEAM: ccpay
    REFORM_SERVICE_NAME: ccpay-bubble
    REFORM_ENVIRONMENT: preview
    NODE_ENV: production
    APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY}
